### ISSUE TITLE
deploy script ran with no error, but matter center app is not deployed

### ISSUE THREAD

**Issue by mvosmer** [Microsoft/mattercenter#227] opened 2016-06-14 13:29 UTC
Hello, I hope somebody can send me in the right direction so i can solve my issue.
I managed to run the deploy script with no errors ( final steps attached to this post).
Then I carried out the instructions in appendix C (step 11 in the guide).
Step 12, the matter center app is not present on https://lialis.sharepoint.com/teams/lialistest
I can add the matter center app via apps from my organization. Then I trust it, but I do not have the deployment options as showed in the guide.
When I access the matter center app it opens, but the links menu, matters and documents) do not respond when I click on them (nothing is responding in the matter center app).
I guess I did something wrong, can somebody help me?

Adding users to group: Lialis Visitors
Successfully added users to group: Lialis Visitors
13-6-2016 22:20:53 - Completed creating site collection
13-6-2016 22:20:53 - Step 15: Provisioning Web dashboard
Deleting matter center pages from: https://lialis.sharepoint.com
Successfully deleted file: MatterCenterHome.aspx
Provisioning matter center pages on: https://lialis.sharepoint.com
Successfully provisioned the matter center page: MatterCenterHome.aspx
Deleting matter center pages from: https://lialis.sharepoint.com
Successfully deleted file: Settings.aspx
Provisioning matter center pages on: https://lialis.sharepoint.com
Successfully provisioned the matter center page: settings.aspx
Deleting matter center pages from: https://lialis.sharepoint.com/teams/lialistest
Provisioning matter center pages on: https://lialis.sharepoint.com/teams/lialistest
Successfully provisioned the matter center page: settings.aspx
Creating configuration list
Deleting matter center pages from: https://lialis.sharepoint.com/sites/appcatalog
Successfully deleted file: documentDetails.aspx
Provisioning matter center pages on: https://lialis.sharepoint.com/sites/appcatalog
Successfully provisioned the matter center page: documentDetails.aspx
13-6-2016 22:21:08 - Completed Provisioning Web dashboard
13-6-2016 22:21:08 - Step 16: Update site collection view with fields

Updating View for site collection Lialis
Lialis site collection view updated with field
13-6-2016 22:21:15 - Step 17: Creating source in event viewer
13-6-2016 22:21:15 - Deployment completed successfully
13-6-2016 22:21:15 - Ended Deployment at: 06/13/2016 22:21:15

**Comment by amitabhm21** [comment] 2016-06-15 20:54
Hi @mvosmer . Would you please go through this thread [https://github.com/Microsoft/mattercenter/issues/169] and see if you have other similar symptoms as well?

**Comment by mvosmer** [comment] 2016-06-22 11:26
Hi, ok, I checked the thread #169, please find below my answers to the questions in this thread.

>> these errors I get in
GenericFunctions
06-22-2016 11:01:04:2537869 - ec095013-d5a3-4711-9b03-3d2b728c2beb
-2146233087
"https://mattercenterlialis.azurewebsites.net" is not the intended audience "9a68eaf3-59fc-46bc-b2a5-2da026c2bebe/mattercenterlialis.azurewebsites.net@7f77abb3-b3d2-49fd-8112-b2eb88596fe4"
SetConstantsResponse
188

MatterCenterMaster
06-22-2016 11:01:05:1765285 - dc09d527-6dc5-4b65-bd9f-1a5449f4e8b8
-2147467261
Value cannot be null.
Parameter name: context
Page_Load
77


$$ Verify that the "Matter Configurations" list exists in the Client site collection.
>> yes its their, but a bit weird see image below
![1](https://cloud.githubusercontent.com/assets/13832135/16264639/fd1a654c-387a-11e6-9f59-37683f6ef70b.jpg)


$$ Verify that the Client term has the custom properties provisioned and that the values are correct. Specifically we want to verify that the ClientURL property is set to the Client site collection URL.
>> picture from my termstore
![2](https://cloud.githubusercontent.com/assets/13832135/16264831/1c645ff6-387c-11e6-95a4-34cc09569816.JPG)

$$ Can you check the value of your Provision_Matter_App_URL in the Microsoft.Legal.MatterCenter.Utility Constansts.resx file? It should be pointed to the MatterCenter app in your App Catalog. For instance if your app catalog is located at:
>> Provision_Matter_App_URL = https://mattercenterlialis.sharepoint.com/sites/catalog/MatterCenter   . I guess this is wrong :-(

**Comment by amitabhm21** [comment] 2016-06-24 23:02
Looks like its wrong from the screenshots.

Once you have confirmed (Constants.RESX file in Utility folder -> value for Provision_Matter_App_URL key).
 
Also check: 
 1. The Client ID and Client Secret generated during SP App registration is correctly populated in SharePointAppWeb -> Web.Config, SharePointAppWeb->App_GlobalResources->Constants.resx, ProviderService -> Web.Config, ProviderService >App_GlobalResources->Constants.resx, MatterCenter -> AppManifest.xml
 
2. Go to Azure Websites, click on Configure tab. In this tab ensure that it has following settings added:
 Encryption_Key & Old_Encryption_Key

**Comment by amitabhm21** [comment] 2016-06-27 22:36
Closing this for now. @mvosmer Please re-open if this issue is not resolved.

**Closed by amitabhm21** 2016-06-27 22:36 UTC
