### ISSUE TITLE
Uploading files to Sharepoint Library failed

### ISSUE THREAD

**Issue by miltonburgos** [Microsoft/mattercenter#679] opened 2017-03-02 18:13 UTC
Hi all, 

We installed all pre-requisites in a Windows 2016 Server. 

We had success deploying Sharepoint Assets following the steps until Step 6.

We are having issues deploying Azure Resources, Office and Exchange Apps on Step 7.
When we run .\AzureResourceGroup.ps1 it throws an error as showed in the image below: 
- Uploading files to SharePoint Library failed
- Updating Office, Outlook and SharePoint App schema files failed

We already checked if all pre-requisites were installed, powershell version, updates on  Windows Server 2016, admin privileges, azure modules installed and so on.

Is there any idea what is going on? What do we need to check?

<img width="695" alt="capture" src="https://cloud.githubusercontent.com/assets/20663138/23520337/4c2c5474-ff59-11e6-9e77-04d38372100d.PNG">

**Comment by allenolayiwola** [comment] 2017-03-06 09:57
Make sure that the ErrorLog.txt file located at ...\tree\master\cloud\src\solution\Deployment\Scripts\Logs has been deleted before running the deployment. The scripts will check this log file and will always fail if the file is not empty. 

Also check to make sure you have administrative rights to the sharepoint site collection. 

Finally delete the web app and try the install again if all the above fails.

**Comment by amitabhm21** [comment] 2017-03-07 21:07
closing this issue as this is a Duplicate of https://github.com/Microsoft/mattercenter/issues/684

**Closed by amitabhm21** 2017-03-07 21:07 UTC
