### ISSUE TITLE
MC2 - Deployment issue UpdateAppConfig code is considering old webapp url format

### ISSUE THREAD

**Issue by luismanez** [Microsoft/mattercenter#387] opened 2016-09-07 06:40 UTC
When UpdateAppConfig.exe tries to Update the XML for the Office/Outlook App, the call to UpdateManifest, is passing flag = false, and that makes that the UpdateManifest code, is threating the Azure webapp URL like the version 1 was (asp.net webforms app), where the URL was like:

https://site.azurewebsites.net/pages/Home.aspx

That's not gonna work with the new azure webapp (SPA + MVC), as there's no any /pages/ folder, and the code raises an exception.

A possible workaround (haven't test it yet), is to change UpdateManifest with:

```c#
if (flag)
{
    clientElement[iterator].Attributes[clientAttribute].Value = excelInput[startPageElement];
}
else if ("iconUrl" == sourceLocation)
{
    clientElement[iterator].Attributes[clientAttribute].Value = excelInput[startPageElement] + previousValue.Substring(previousValue.IndexOf(ConstantStrings.IMAGES_ICON, StringComparison.OrdinalIgnoreCase));
}
else
{
    clientElement[iterator].Attributes[clientAttribute].Value = excelInput[startPageElement];
}
```

**Comment by WilsonReddy** [comment] 2016-09-07 18:18
@luismanez / @pavanpadavala can you verify and submit pullrequest for this one?

**Comment by luismanez** [comment] 2016-09-08 08:46
With yesterday's commit, that UpdateAppConfig.exe seems to be called during the Azure deployment steps, and I got more issues, but not sure if my code above now is still valid.

Also, I'm getting 500 error once the web app is deployed to Azure, and I'm not able to find the reason (I'm getting none-sense messages around favicon.ico requests)

Please @WilsonReddy / @pavanpadavala can you confirm that you can make a clean deploy to a new tenant with the current HelperUtilities/Scripts/Code/Guides ?? cos I'm going crazy :(

The first Deploy.ps1 script works fine. Then, most of the Azure deployment stuff seems ok, but at some point, it runs Deploy-SPOFiles.ps1and there, first I get an error:

```
Deleting matter center pages from: https://my_tenant.sharepoint.com
Exception while Provisioning Matter Center page: List 'Site Pages' does not exist at
 site with URL 'https://my_tenant.sharepoint.com'.
```
which makes sense, as at some point, one of the previous scripts enables Publishing on the root site, so there's no "Site Pages" ...

then, the script seems is running the UpdateAppConfig.exe, and again, getting same issue with the /Pages/ url when trying to update the Outlook app schema...

```
Updating app schema files
C:\mattercenter2\tree\master\cloud\src\deployments
Updating Microsoft.Legal.MatterCenter_OutlookManifest.xml file
Message: StartIndex cannot be less than zero.
Parameter name: startIndex
Stacktrace:    at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateManifest(Strin
g inputXMLFile, Dictionary`2 excelInput, String sourceLocation, String defaultValue,
 String startPageElement, Boolean flag)
Message: The given key was not present in the dictionary.
```

Please, review the entire deployment process and let me know if I can help with whatever.
Many thanks.

**Comment by amitabhm21** [comment] 2016-09-08 23:11
Hey @luismanez we have fixed these issues and will merge code in master.
Since you have identified the root cause and also the code, would you please submit a pull request as suggested by @WilsonReddy? That way we would have  community contributions and will encourage the rest of the community.

Appreciate your help !

**Comment by luismanez** [comment] 2016-09-09 12:10
Thanks @amitabhm21 I've done Pull Request with that change (actually the code was already updated from someone else in the team, but I've refactored it a little).
https://github.com/Microsoft/mattercenter/pull/399

Keep in mind that I mentioned more issues during the deployment process, and I'm not sure how to fix them, as I don't have enough knowledge around the entire deployment process and new architecture.

Let me know how else I can help.

**Comment by amitabhm21** [comment] 2016-09-09 18:42
Thans Much! The issues that you have identified are fixed and merged with master every day as part of the daily builds. Keep providing feedback and report issues. Greatly appreciated.

**Comment by amitabhm21** [comment] 2016-09-12 18:53
Fixed multiple issues.

**Closed by amitabhm21** 2016-09-12 18:53 UTC
