### ISSUE TITLE
Installation step 11 failing

### ISSUE THREAD

**Issue by PieterVeenstra** [Microsoft/mattercenter#29] opened 2015-12-21 10:37 UTC
During this step 11 I'm getting a time out in the following line:
& "$HelperPath\Microsoft.Legal.MatterCenter.UpdateListPermissions" $Username $Password
        }  

I decompiled the UpdateListPermissions binary and  the UpdateSendMailListPermissions method isn't finding the Sendmail list.

This section of the codde doesn't make much sense for an installation process.

*do
			{
				Console.Write(".");
				Thread.Sleep(30000);
				clientContext.Load<ListCollection>(lists, new Expression<Func<ListCollection, object>>[]
				{
					(ListCollection lists) => lists.Include(new Expression<Func<List, object>>[]
					{
						(List list) => list.Title,
						(List list) => (object)list.HasUniqueRoleAssignments
					})
				});
				clientContext.ExecuteQuery();
				list = lists.Cast<List>().FirstOrDefault((List list) => list.Title == listName);
				num++;
			}
			while (list == null && 20 > num);*

So the code is looking for a list and then we're waiting for a while and trying the same thing 20 times. If the list doesn't exist then why would it appear at a later stage. unless this list is something that I should create manually.

The error log is giving: 

Message: SendMail list was not created successfully at https://mytenant.sharepoint.com/sites/AppCatalog/MatterCenter occurred at 21/12/2015 10:41:18

**Comment by sunnymistry** [comment] 2015-12-21 17:28
Thank you Pieter for posting this issue. When the Matter Center SharePoint app is being installed, it creates a List which has an Email workflow attached to it. Once the app is successfully installed you can access the list over here:  https://mytenant.sharepoint.com/sites/AppCatalog/MatterCenter/SendEmail. 

But the time taken to complete the installation of this app varies on tenant's. Once app installation is complete, the list is created (as it is part of app installation process) and thus confirms that the app has successfully installed.

**Comment by PieterVeenstra** [comment] 2015-12-21 17:30
Ok, so this is most likely related to the issues I'm having in step 8 then. Thanks for confirming where the references to the Beta name of the app are still there but the app itself doesn't have the word beta anymore.

**Comment by SFghub** [comment] 2015-12-23 22:24
I'm also having an issue on step 11, though I'm not sure how to troubleshoot where its going wrong, here is a screenshot of the error, logs don't tell me anything afais, any help appreciated:

![mcerror](https://cloud.githubusercontent.com/assets/16419194/11986132/000e5f80-a99a-11e5-91f7-77fca2f91c3e.PNG)

**Comment by PieterVeenstra** [comment] 2015-12-24 07:45
That us slightly different your status says installing.

In my case in says initialized.

Also for me the app failed to be added to a SharePoint site.
________________________________

**Comment by s-KaiNet** [comment] 2016-01-05 14:20
@SFghub I have exactly the same issue with nasty `Status:Failed to install apps to SharePoint.`  
How did you solve it?

**Comment by s-KaiNet** [comment] 2016-01-06 16:12
Answering own question - I had a problem with local date time which is not listed on my local computer. So to resolve this issue I changed app catolog time zone to something more known then `Minsk +3` - to east time. This issue connected with workflow persistence in project.

**Comment by DaveyDoo** [comment] 2016-01-12 21:35
I am seeing the same issue as SFghub and s-KaiNet.  Unfortunately, I'm in the Eastern time zone, so I don't see how s-KaiNet's fix will help me.  Nothing gets logged in ErrorLog.txt

**Comment by MatthewSammut** [comment] 2016-01-14 16:21
I'm also getting the same error exactly as @SFghub. Are there any updates regarding this error? 

@s-KaiNet - Which setting have you changed exactly? and why did you choose east time? I mean, what did you had to match it to? Note I'm in London. I checked that the local in site settings on the app catalogs site collection to GMT (as I'm in London) but didn't do any difference.

Have been trying to figure this out for a couple of hours now, but don't really know where to start looking. No much useful logging as far as I can see. Any recommendations on how one would go about troubleshooting this?

**Comment by bblackwood1** [comment] 2016-01-15 22:31
@SFghub did you check your sync/elements.xml in the Microsoft.Legal.MatterCenter section?  I had this exact same issue and it was because I misspelled my site name in the URL action... may not help but it is what got me past that problem

**Comment by bblackwood1** [comment] 2016-01-20 16:25
Okay I think I have this thing figured out... @SFghub , @MatthewSammut  here is what I found.

There were three issues that I had with the appmanifest files.

1) in the Microsoft.Legal.MatterCenter appmanifest.xml I had a space in line 4 behind matter center.  That had to be taken out.

2) I didn't completely rewrite the start page link so I just added my mattercenter .azurewebsites.(the rest) but noticed that azurewebsites said "azurewebsite" instead so I had to add the "s" to the back end of it.

3) the exact same issue with the azurewebsites missing the s but under the Microsoft.Legal.MNatterCenter.OneDriveRibbon appmanifest.xml file.

Please let me know if this has helped you.

Brian

**Comment by Majovero** [comment] 2016-01-26 23:25
Did you guys ever come up with a fix for this? I get the same hang in step 11. I have triple checked everything you guys have said previously. Everything seems to be in order. Does anyone know what exactly is happening at this stage. Is there some other workaround? Also, @PieterVeenstra how are you getting your logs? Any help greatly appreciated. -Eric

**Comment by tilldabillswin** [comment] 2016-01-27 02:19
Same issue here. I did have the issues with azurewebsite instead of azurewebsites in the xml files, but I've corrected them and deployment still fails. Is there a way to debug the deployment to get more information on what's actually happening? @SFghub , @MatthewSammut

**Comment by bblackwood1** [comment] 2016-01-27 14:49
I wasn't able to figure out a good way aside from finding the individual powershell that was failing and then digging into that script until I found where the problem was. Try changing the scripts here is a link
https://gist.github.com/s-KaiNet/45c54432b47bfb2e5db7  It reorders a few things and that may help you get past your current issue.  Let me know if that helps.

**Comment by bryanlibin** [comment] 2016-01-27 21:16
I also got the same error in Step 11 - " Adding and installing apps to SharePoint and Office failed". There is nothing in the ErrorLog.txt and Log.txt for trouble-shooting. Any tips on identifying the root cause? Thanks!

**Comment by Majovero** [comment] 2016-01-27 21:35
I was finally able to get this to go thru after reading EVERY SINGLE POST on this forum. All the little fixes and and tricks helped, but then there were a couple of small things that caught debugging that could have been errors on my part or the script as I downloaded it.

**Comment by kkhipple** [comment] 2016-02-01 01:45
same issue here as well.  any advice on what this could be?  @PieterVeenstra @sunnymistry 
I've even looked at what @bblackwood1 had pointed out including testing out his powershell updates.  no luck.

**Comment by Majovero** [comment] 2016-02-01 06:46
@kkhipple most people here are using the upload script provided by @s-KaiNet which bypasses a lot of the errors and then proceed to fix those errors afterward. I think the success of the original script is based on your specific deployment of your base Windows Server infrastructure, i.e. is everything in the could; is AD located onsite; using online VS, etc. It would be nice to know the exact infrastructure used by the MS development team @sunnymistry.

**Comment by kkhipple** [comment] 2016-02-01 06:58
@Majovero thx for following up and I believe I did review @s-KaiNet's powershell script https://gist.github.com/s-KaiNet/45c54432b47bfb2e5db7 and updating my script as well.  I still ran into the same error at step 11.

I'm installing it to a demo o365 tenant and agree that a bit more details would absolutely help as I know there are a few law firms who are waiting to get their hands on matter center.  any guidance is much appreciated!

**Comment by stefvanhooijdonk** [comment] 2016-02-17 10:46
If the App fails to install during Step 11; check if you have not in fact blocked SharePoint 2013 workflows at the tenant level. (SharePoint Admin -> Settings)

**Closed** 2016-03-16 19:04 UTC
