### ISSUE TITLE
Scripted Install fails during STEP 11 after Matter Center has been successfully loaded and installed 

### ISSUE THREAD

**Issue by sean8781** [Microsoft/mattercenter#104] opened 2016-03-15 08:26 UTC
Hello,

My scripted install fails, and I still receive the error during install after making the changes suggested in #80  (updating URL to be MatterCenter)

Here is a screenshot and the error messages I received after installing MatterCenter:
![image](https://cloud.githubusercontent.com/assets/6021353/13771304/04abc3de-ea4a-11e5-89de-15af70fc39c1.png)
> 3/15/2016 00:57:35 - Status:Installing3/15/2016 00:57:36 - .3/15/2016 00:57:46 - .3/15/2016 00:57:56 - Matter Center has been successfully loaded and installed
> 3/15/2016 00:57:57 - Status:3/15/2016 00:57:57 - Disabling SideLoading feature on site https://hayesq.azurewebsites.net
> 3/15/2016 00:57:57 - SideLoading disabled on site https://hayesq.sharepoint.com/sites/catalog
`Message: Cannot contact site at the specified URL https://hayesq.sharepoint.com/sites/catalog/ProvisionDMSMatter. There is no Web named "/sites/catalog/ProvisionDMSMatter/_vti_bin/sites.asmx".
Stacktrace:    at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()
   at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.Legal.MatterCenter.Common.ConfigureSharePointContext.ConfigureClientContext(String url, String userId, String password, Boolean isDeployedOnAzure) in C:\MC\Helper Utilities\Microsoft.Legal.MatterCenter.HelperUtilities\Microsoft.Legal.MatterCenter.Common\ConfigureClientContext.cs:line 56
   at Microsoft.Legal.MatterCenter.UpdateListPermissions.Program.Main(String[] args) in C:\MC\Helper Utilities\Microsoft.Legal.MatterCenter.HelperUtilities\Microsoft.Legal.MatterCenter.UpdateListPermissions\Program.cs:line 54`
> 3/15/2016 00:58:00 - Adding and installing apps to SharePoint and Office failed
> 3/15/2016 00:58:00 -
> 3/15/2016 00:58:00 - Reverting till step 11 

Looking at the message, I noticed in my app.config: 
`C:\MC\Helper Utilities\Microsoft.Legal.MatterCenter.HelperUtilities\Microsoft.Legal.MatterCenter.UpdateListPermissions\App.config`

Should the value be changed to: **MatterCenter**?
`<add key="ProvisionMatterAppName" value="ProvisionDMSMatter"/>`  

Thank You! 
-Sean

**Comment by sean8781** [comment] 2016-03-15 08:38
OK, It looks like changing the value of the ProvisionMatterAppName to "MatterCenter" actually fixed this problem.. so It had to be changed in the app.config within the HelperUtilities:

`Helper Utilities\Microsoft.Legal.MatterCenter.HelperUtilities\Microsoft.Legal.MatterCenter.UpdateListPermissions\App.config`

**Comment by amitabhm21** [comment] 2016-03-16 18:58
Closing this as the issue is resolved.

**Closed by amitabhm21** 2016-03-16 18:58 UTC
