### ISSUE TITLE
Matter Center Application Error

### ISSUE THREAD

**Issue by bblackwood1** [Microsoft/mattercenter#52] opened 2016-01-06 19:39 UTC
I have installed Matter Center and I can not figure out this issue. 
![mcerror](https://cloud.githubusercontent.com/assets/16137126/12152517/d2739644-b47a-11e5-98e6-540751379dc6.png)

**Comment by johnnycardy** [comment] 2016-01-07 10:06
It's just a generic error that could mean anything. Likely a part of the install process went wrong. Check the browser tools for ajax requests that returned an error. Chrome -> F12 -> Network tab -> refresh page and post a screenshot.

**Comment by bblackwood1** [comment] 2016-01-07 14:12
![mcerror2](https://cloud.githubusercontent.com/assets/16137126/12172409/5340c6de-b516-11e5-9d94-9239a73a4a2e.png)
![mcerror3](https://cloud.githubusercontent.com/assets/16137126/12172411/57a7d67c-b516-11e5-9c79-bf161def03a3.png)
Here are the network and console screenshots

**Comment by LeoConniff** [comment] 2016-01-07 23:38
Based on the screenshot that you provided, you are using the wrong url for your search service.  I did a quick check and confirmed that the domain of the url used here for the service is actually your web app domain.  As a result, you are getting a 404 since the search service doesn't exist on that website.  You can update url by downloading the constants.resx from the app global resources folder in your web app azure site.  Then update the following values and reupload the file:
 - Search_Service_Url
 - Legal_Briefcase_Service_Url
 - Matter_Provision_Service_Url

**Comment by bblackwood1** [comment] 2016-01-08 15:39
Thank you Leo that solved at least that problem and now has uncovered another.  
![mcerror4](https://cloud.githubusercontent.com/assets/16137126/12201753/b2f963ee-b5eb-11e5-8b34-b7510b08724e.png)

**Comment by johnnycardy** [comment] 2016-01-08 15:43
`Access-Control-Allow-Origin`, in the web.config of your ProviderService project, must begin with `https://`, ie:

    <add name="Access-Control-Allow-Origin" value="https://rlmattercenter.azurewebsites.net" />

**Comment by bblackwood1** [comment] 2016-01-08 16:36
First let me say thank you for the help so far!  That worked... I didn't realize that I left the https off of it.  On to the next problem.  When I go to create a new matter I get the ReferenceError oGlobalConstants is not defined error.
![mcerror5](https://cloud.githubusercontent.com/assets/16137126/12203266/aaf4cba4-b5f3-11e5-9952-935a650394e3.png)

**Comment by johnnycardy** [comment] 2016-01-08 16:50
I am currently struggling with that one myself....

**Comment by bblackwood1** [comment] 2016-01-08 17:05
did any of your sample data from the spreadsheet get uploaded?  If so where?

**Comment by johnnycardy** [comment] 2016-01-11 09:15
A number of lists were created, but don't have data in them. I would have expected MatterCenterMatters to be populated at least...but no.

By the way, I got past the oGlobalConstants error. An exception was being thrown on the web server because an encryption key wasn't set (because that part of the install failed for me). I fixed it manually. My advice is to attach a debugger to the web server and the service server to watch for exceptions.

**Comment by bblackwood1** [comment] 2016-01-13 15:03
Once you got the global constants error sorted out were you able to create a matter? 
Mine have to do with application insights (which I removed from the project so that doesn't really make sense to me) 
the matter provision service url (which is for a dev site) so why would that stop me?
And the central repository url... not really sure about that one

**Comment by johnnycardy** [comment] 2016-01-13 15:40
I wasn't. I am now, but there was a lot of debugging, fixing, and commenting out bits of code, before I was able to create a matter! I didn't document it because most of it was due to the installation having failed.

Attach a debugger to the web site, the service site, and watch for network activity and javascript errors... it's not smooth riding!

**Comment by bblackwood1** [comment] 2016-01-13 15:48
so you didn't use the browser debugger?  I tried allowing debugging in the web.config so I could f5 but that did not work at all... which one did you end up using?  Does the one that you can use in azure work?

**Comment by johnnycardy** [comment] 2016-01-13 15:54
Yeah, a browser debugger (ie. F12 tools) to see what the AJAX requests are returning.
Also, attaching to the azure websites via azure remote debugging. F5 will never work. Here's how to attach: http://blogs.msdn.com/cfs-filesystemfile.ashx/__key/communityserver-blogs-components-weblogfiles/00-00-01-13-25/0363.Jaime-Espinosa_2D00_FIGURE-1_2E00_.PNG

**Comment by bblackwood1** [comment] 2016-01-13 16:50
Also during your debugging did you have to run that script every time you made a change?

**Comment by johnnycardy** [comment] 2016-01-14 11:41
No, just right click on the solution in VS -> Deploy. Choose the azure site to deploy to. In the 'preview' pane, you will want to check the web.config for differences because you probably don't want to overwrite it.

![image](https://cloud.githubusercontent.com/assets/904610/12323500/95b932f6-bab3-11e5-802c-8d02cd2d58eb.png)

**Comment by bblackwood1** [comment] 2016-01-14 23:27
Okay Johnny hopefully this is the last part of this ridiculous puzzle to solve... but not likely.  I have found all of the java files that are erroring out my global constants and commented out one and then the next one would be the error.  Am I missing something simple here?  This is frustrating as can be for me.
![mcerror6](https://cloud.githubusercontent.com/assets/16137126/12340985/f9f85d70-bae3-11e5-93ef-b14e1c37d9f1.png)
![mcerror7](https://cloud.githubusercontent.com/assets/16137126/12340990/fd9c9aae-bae3-11e5-9c13-5258638a5619.png)

again I appreciate all of your help with this

**Comment by johnnycardy** [comment] 2016-01-15 07:33
Don't comment out any JavaScript files. The error is caused in the web application. Attach the debugger to it, turn on exceptions, and go that route.

Look in the `GenericFunctions->SetResponse` method:

`response.Write(SetGlobalConfigurations("Constants", UIConstantStrings.GlobalConstants, Enumerators.ResourceFileLocation.App_GlobalResources));`

That's the line where `oGlobalConstants` is defined. Obviously `SetResponse` is erroring out before it gets that that line - you need to find out why.

**Comment by sunnymistry** [comment] 2016-01-19 20:11
I would check following for resolving this:
a. Go to Constants.RESX file in Utility folder
b. Check the value for Provision_Matter_App_URL key
c. Ensure that this URL is correct. it should be https://<tenantname>.sharepoint.com/sites/<catalogname>/MatterCenter

If above settings is correct, than I would check 
a. The Client ID and Client Secret generated during SP App registration is correctly populated in SharePointAppWeb > Web.Config, SharePointAppWeb>App_GlobalResources>Constants.resx, ProviderService > Web.Config, ProviderService >App_GlobalResources>Constants.resx, MatterCenter > AppManifest.xml
b. Go to Azure Websites, click on Configure tab. In this tab ensure that it has following settings added:
Encryption_Key & Old_Encryption_Key

**Comment by bblackwood1** [comment] 2016-01-20 19:12
I checked the resx file in the utilities and the url was correct (unless that // between sites and mattercenter was intended.  I also checked the SP app reg and the encryption_key and old_encryption_key were both populated (with the same data) in azure

**Comment by bblackwood1** [comment] 2016-01-20 20:42
@sunnymistry are the encryption key and old encryption supposed to be populated with the client id?

**Comment by sunnymistry** [comment] 2016-01-20 21:06
The encryption key can we any key using which you want to encrypt the data. We recommend it to be a GUID so that it is difficult to decipher.

Another thing if you can check if the would be the HostedAppHostNameOverride app settings in SharePointAppWeb and ProviderService solution. It should only have your UI site URL without HTTPS. For e.g. it should be in the format of <WebsiteName>.azurewebsites.net

**Comment by bblackwood1** [comment] 2016-01-20 21:11
Okay thanks  it was a guid.

As far as the format of the hostedapphostnameoverride's are only the site url

**Comment by sunnymistry** [comment] 2016-01-20 23:18
Did you check your Azure Storage Logs in case if any error is getting logged over there? 

Check following if you are unable to find the any errors in your Azure Storage Logs.
a. Check the Provision_Matter_App_URL from Utility > Constants File if it is valid
b. The Manual step to grant Permission to MatterCenter app on SharePoint
c. The Client ID and Client Secret used in Web.Config are they accurate

**Comment by bblackwood1** [comment] 2016-01-21 14:54
@sunnymistry This is the one that seems the most relevant...
"https://mattercenter.azurewebsites.net" is not the intended audience "69cd55c6-7afd-41h8-93b3-231d196fd1b1/mattercenter.azurewebsites.net@75554cb3-ea04-40d0-9587-451428ab862b"

I changed the address to just matter center, that's not the way that it looks.  Anyway does that mean that I put the mattercenter site somewhere in the code that I shouldn't have?  I will go through the document again to make sure but I have gone through this at least a dozen times so I am not sure where the mistake is

**Comment by bblackwood1** [comment] 2016-01-21 14:58
Also it tells me that it is erroring out in GenericFunctions.cs line 188.

**Comment by bblackwood1** [comment] 2016-01-21 17:27
@sunnymistry I found the issues but am quite confused by it... My Provision_Matter_app_URL was correct on my local machine but incorrect on my azure server.  I found it in the bin folder and the value was https://sharepoint.com/sites/catalog/ProvisionDMSMatter instead of https://sharepoint.com/sites/catalog/MatterCenter... I guess this got corrupted during the powershell script but I changed it manually and all of my global constant errors went away.  What would have caused this?

**Comment by DaveyDoo** [comment] 2016-01-22 15:35
Nice catch!  I can verify that the value for Provision_Matter_app_URL is XXX.sharepoint.com/sites/catalog/ProvisionDMSMatter in the deployed service/bin/Constants.resx file, even though its value is XXX.sharepoint.com/sites/catalog/MatterCenter in the Microsoft.LEgal.MatterCenter.Utility project's Constants.resx file (I'm pretty sure that is the source).
I don't see anything in the PowerShell that could have changed that. Interesting.

**Comment by sunnymistry** [comment] 2016-01-23 00:58
Only thing now I can see is the build published on Azure is different from the build present on your local machine.

**Comment by sunnymistry** [comment] 2016-02-09 19:23
@DaveyDoo , wanted to follow up and see if the install of MC was completed on your Demo tenant?

**Comment by DaveyDoo** [comment] 2016-02-09 19:40
Yes, we have it up and running.

**Closed** 2016-02-09 19:40 UTC
