### ISSUE TITLE
"The given guid does not exist in the term store" when creating Matter

### ISSUE THREAD

**Issue by ADOrigin** [Microsoft/mattercenter#124] opened 2016-03-23 04:06 UTC
When I try to create a new matter, I get through to the 3rd step ("Create and Notify") on MatterProvision.aspx OK.  When I click the "Create" button, it gets to step 2 ("Step 2/3: Assigning permissions to matter library and OneNote library, associating Content Types, creating view and matter landing page..."), then I get the following error message displayed on the page:

An error has occurred and the matter was not created. Error Code: -2146233088

If I look in the log table, I see the following details:
PartitionKey: MatterProvision
ErrorCode: -2146233088
LineNumber: 600
LogMessage: The given guid does not exist in the term store
MethodName:  AssignContentType

I'm not sure exactly what GUID it's searching for or which item in the term store it is trying to find.  I've made sure the content types have all been published, but that doesn't seem to have made a difference.

**Comment by premchandpl** [comment] 2016-03-23 22:25
@ADOrigin  

The issue is with TaxonomyHiddenList present in your Site Collection. Foreach term that has been used in your site collection, an entry of the term will be made in the TaxonomyHiddenList. If the term GUID in the TaxonomyHiddenList and the Guid of the same Term in the Term Store doesn’t match we will get that issue. 

This issue will occur if the term stored got recreated due to re-deployment, and the TaxonomyHiddenList not getting updated with the new term guids

The solution to this one will be, clear your TaxonomyHiddenList and try to create a new matter. I have faced the same issue and I used this approach and the issue got resolved 

The url for taxonomy hidden list will be:

https://MatterSiteCollectionUrl/_layouts/15/start.aspx#/Lists/TaxonomyHiddenList/AllItems.aspx

**Comment by ADOrigin** [comment] 2016-03-23 22:35
Hi, thanks for replying.  I have redeployed this several times, so your suggestion makes sense.  However, I had a look and the TaxononmyHiddenList doesn't seem to contain any items at all, so there's nothing there for me to delete.

Thanks anyway for your suggestion.

**Comment by premchandpl** [comment] 2016-03-23 23:30
@ADOrigin 
Can you also verify that you have emptied TaxonomyHiddenList in all the matter center related site collection. Especially, the site collection where the matter center are getting created

**Comment by ADOrigin** [comment] 2016-03-24 01:54
Yeah, I checked all of the site collections, none of them have anything in this list.

I wasn't actually aware this list even existed - is this part of Matter Center, or is it a standard SharePoint online thing (this is my first time using SP online, too, so I'm still not sure how it all works on that side)?

**Comment by premchandpl** [comment] 2016-03-24 03:03
Its not related to Matter Center. Its SharePoint OOTB list.

**Comment by sunnymistry** [comment] 2016-04-04 17:42
@ADOrigin , If the Hidden List is empty and does not contain any terms, the next thing to do over here is to update the mapping of AreaOfLaw and SubAreaofLaw Site columns in ContentTypeHub. Refer to #63 for details about this change.

**Comment by ADOrigin** [comment] 2016-04-05 06:15
Thanks for your reply.  I have already updated these mappings but it hasn't helped.

This thing just does not want to work for me...

**Comment by sunnymistry** [comment] 2016-04-08 15:42
After updating the mapping, did you republish the content type? It take some time for the published content type to replicate across your tenant. If yes, can you check in the client site collection that the updated mappings are indeed reflected.

**Comment by ADOrigin** [comment] 2016-04-14 02:45
Yeah, I republished the content types.

As for checking the client site collection... so I should go into the site columns in that site and make sure they're the same as in the content type hub (i.e. PracticeGroup -> Practice Groups, Area of Law -> Litigation, SubAreaOfLaw -> Intellectual Property)?

**Comment by sunnymistry** [comment] 2016-04-19 21:46
Yes this is correct. Make sure that the Site Column in the Site Collection is pointing to correct Term Set which you set in Content Type Hub

**Comment by sramangit** [comment] 2016-06-09 03:25
I'm stuck in the same place :(. I tried everything suggested above. Did this get resolved?

**Comment by ADOrigin** [comment] 2016-06-09 04:32
We eventually got it working by trying something a little different.  Instead of mapping PracticeGroup -> Practice Groups, AreaOfLaw -> Litigation, SubAreaOfLaw -> Intellectual property, we mapped all three to Practice Groups.

**Comment by anandmp** [comment] 2017-01-18 15:54
While creating the matter, I am stuck with the error "The given guid does not exist in the term store". I tried redeploying everything as per the installation document. But still I am not able to resolve this error. I would appreciate if anyone has suggestions to resolve this issue.

**Comment by WilsonReddy** [comment] 2017-01-31 17:08
@anandmp This issue happens if content type is not published. It may take up to 24 hours to reflect published content type in all site collections. Ensure content types are published as mentioned in deployment document. if issue still exist clean taxonomyhidden list as mentioned above.

**Comment by anandmp** [comment] 2017-02-08 15:02
@WilsonReddy Thanks for the information. We are still getting the same error. The taxonomy hidden list is already empty. For the published content types, we had waited for more than 24 hours. But it is still showing the same error.

Here is the detailed error that we get.
 
**Description** Error occured in the system. Please contact the administrator
**Message** The given guid does not exist in the term store
**ErrorCode** 500
**MethodName** GetWSSId
**ClassName** SPContentTypes
**LineNumber**  237
**StackTrace** at Microsoft.Legal.MatterCenter.Repository.SPContentTypes.GetWSSId(ClientContext clientContext, MatterMetadata matterMetadata, FieldCollection fields) in C:\Project\mattercenter\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Service\Microsoft.Legal.MatterCenter.Repository\SharePointInfo\SPContentTypes.cs:line 237
at Microsoft.Legal.MatterCenter.Repository.SPContentTypes.SetFieldValues(ClientContext clientContext, IList`1 contentTypeCollection, List matterList, MatterMetadata matterMetadata) in C:\Project\mattercenter\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Service\Microsoft.Legal.MatterCenter.Repository\SharePointInfo\SPContentTypes.cs:line 170
at Microsoft.Legal.MatterCenter.Repository.SPContentTypes.AssignContentTypeHelper(MatterMetadata matterMetadata, ClientContext clientContext, IList`1 contentTypeCollection, Client client, Matter matter) in C:\Project\mattercenter\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Service\Microsoft.Legal.MatterCenter.Repository\SharePointInfo\SPContentTypes.cs:line 104
at Microsoft.Legal.MatterCenter.Web.Common.MatterProvision.AssignContentType(MatterMetadata matterMetadata) in C:\Project\mattercenter\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Web\Common\MatterProvision.cs:line 841
at Microsoft.Legal.MatterCenter.Service.MatterController.AssignContentType(MatterMetadata matterMetadata) in C:\Project\mattercenter\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Web\Controllers\MatterController.cs:line 942

**Comment by premchandpl** [comment] 2017-02-17 07:33
@anandmp I think we have addressed this issue and we are resolving it

**Closed by premchandpl** 2017-02-17 07:33 UTC
